apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  template:
    spec:
      containers:
        - name: lemonldap-ng-controller
          image: lemonldapng/lemonldap-ng-controller:0.2.0-dev
          args:
            - /lemonldap-ng-controller
            - --alsologtostderr
            - --configmap=$(POD_NAMESPACE)/lemonldap-ng-configuration
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
          - name: copy-portal-skins
            mountPath: /srv/var/lib/lemonldap-ng/portal/skins
        - name: nginx-ingress-controller
          volumeMounts:
          - name: copy-portal-skins
            mountPath: /var/lib/lemonldap-ng/portal/skins
      volumes:
        - name: copy-portal-skins
          emptyDir: {}
